### ISSUE TITLE
[2.0] Refactor TODO list

### ISSUE THREAD

**Issue by SammyK** [SammyK/FacebookQueryBuilder#7]
TODO list for version 2.0.

- [x] Update to Facebook SDK 4.1
- [x] Remove dependencies on statics
- [ ] Consider multi-id-request support (see #16)
- [x] Update docs

This will be a big breaking change upgrade but it'll be for the better. Working with multiple apps will be easier and since SDK 4.1 is hella better, there will be more fallbacks to their native objects. :)

**Comment by SammyK** [comment]
Version 2.0 pivoted the package and it is no longer dependent on the Facebook PHP SDK.
